// Prompt engine — generates personalized prompts based on which buckets are answered
// Prompts expand as more buckets are completed
// This file is on the prompt-library branch so it can be updated/deployed independently

export interface JournalPrompt {
  id: string;
  text: string;
  followUp?: string;
  pattern: string;
  timeOfDay?: "morning" | "evening" | "any";
  type: "reflection" | "tracking" | "action" | "grounding";
}

export const promptLibrary: Record<string, JournalPrompt[]> = {
  adhd: [
    {
      id: "adhd-1",
      text: "What's the thing you're avoiding right now? Don't explain why — just name it.",
      followUp: "What's the smallest possible first step? Like, embarrassingly small.",
      pattern: "adhd",
      timeOfDay: "morning",
      type: "action",
    },
    {
      id: "adhd-2",
      text: "When did you disappear into something today? What was it?",
      followUp: "Was it something you enjoyed or something you got stuck on?",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "adhd-3",
      text: "What did your brain latch onto today that wasn't what you were supposed to be doing?",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "adhd-4",
      text: "Battery check: what drained you today and what charged you up?",
      pattern: "adhd",
      timeOfDay: "any",
      type: "tracking",
    },
    {
      id: "adhd-5",
      text: "What's something you actually finished today? Even tiny. Write it down before your brain deletes it.",
      followUp: "Seriously, your brain will not remember this later. That's why we're here.",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "adhd-6",
      text: "You know that thing you keep meaning to do? The one that's been on your list for weeks? What's the actual blocker — not the excuse, the real thing.",
      followUp: "Is it boring, scary, unclear, or too big to start?",
      pattern: "adhd",
      timeOfDay: "morning",
      type: "action",
    },
    {
      id: "adhd-7",
      text: "What did you hyperfocus on today? Was it useful or did it eat your whole afternoon?",
      followUp: "What would you need to harness that instead of being consumed by it?",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "adhd-8",
      text: "How many tabs are open in your browser right now? In your brain? Same energy?",
      followUp: "Pick one brain tab to close tonight. Just one.",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "grounding",
    },
    {
      id: "adhd-9",
      text: "What's something you started today but didn't finish? No shame — just name it and where you stopped.",
      followUp: "What would it take to pick it back up tomorrow? Not finish it. Just pick it up.",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "adhd-10",
      text: "If someone asked what you did today, what's the first thing that comes to mind? Now what did you actually spend the most time on?",
      followUp: "Is there a gap between those two answers? That's not a failure. It's data.",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "adhd-11",
      text: "What's one thing you can do in the next 10 minutes that your future self will thank you for?",
      followUp: "Not the most important thing. The easiest one you'll actually do.",
      pattern: "adhd",
      timeOfDay: "morning",
      type: "action",
    },
    {
      id: "adhd-12",
      text: "Did you eat today? Like actually eat, not just coffee and vibes?",
      followUp: "What's one basic need you skipped today that you can still catch?",
      pattern: "adhd",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "adhd-13",
      text: "What's the loudest thing in your head right now? Not the most important — the loudest.",
      followUp: "Is it worth the volume it's taking up?",
      pattern: "adhd",
      timeOfDay: "any",
      type: "reflection",
    },
  ],
  anxiety: [
    {
      id: "anx-1",
      text: "What's spinning in your head right now? Just dump it out. No organizing needed.",
      followUp: "Of all that, what's actually likely to happen vs what's just your brain being loud?",
      pattern: "anxiety",
      timeOfDay: "morning",
      type: "reflection",
    },
    {
      id: "anx-2",
      text: "What did you replay in your head today? The thing you keep going back to.",
      followUp: "If your best friend told you they were looping on this, what would you tell them?",
      pattern: "anxiety",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "anx-3",
      text: "Scan your body right now. Jaw, shoulders, stomach, hands. Where are you holding tension?",
      followUp: "Try softening that spot for 30 seconds. Just notice it.",
      pattern: "anxiety",
      timeOfDay: "any",
      type: "grounding",
    },
    {
      id: "anx-4",
      text: "What's the worst case your brain is running? Now write the best case and the most realistic one.",
      pattern: "anxiety",
      timeOfDay: "any",
      type: "action",
    },
    {
      id: "anx-5",
      text: "Anxiety today: was it a background hum or a full takeover? What set it off?",
      pattern: "anxiety",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "anx-6",
      text: "What's something you're dreading tomorrow? Walk through what would actually happen if it went fine.",
      followUp: "Not perfectly. Just fine. Ordinary. Okay.",
      pattern: "anxiety",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "anx-7",
      text: "Breathe in for 4, hold for 4, out for 6. Do that three times. Now write how you feel.",
      followUp: "Your nervous system can't be anxious and breathe slowly at the same time. Biology cheat code.",
      pattern: "anxiety",
      timeOfDay: "any",
      type: "grounding",
    },
    {
      id: "anx-8",
      text: "What evidence do you have that the thing you're worried about is actually happening?",
      followUp: "Now what evidence do you have that it isn't?",
      pattern: "anxiety",
      timeOfDay: "any",
      type: "action",
    },
    {
      id: "anx-9",
      text: "When did you feel safe today? Even for a second. Even if you had to remind yourself.",
      followUp: "What made that moment feel safe? Can you make more of that?",
      pattern: "anxiety",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "anx-10",
      text: "What's the story you're telling yourself about what's going to happen? Whose voice is telling it?",
      followUp: "Is it yours, or is it someone else's voice you internalized?",
      pattern: "anxiety",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "anx-11",
      text: "If your anxiety had a volume knob, where is it right now? 1 (barely there) to 10 (can't think straight).",
      followUp: "What was it this morning? What moved it?",
      pattern: "anxiety",
      timeOfDay: "any",
      type: "tracking",
    },
    {
      id: "anx-12",
      text: "What's something you can control right now? Not everything. One thing.",
      followUp: "Now do it. Even if it's tiny. Especially if it's tiny.",
      pattern: "anxiety",
      timeOfDay: "morning",
      type: "action",
    },
    {
      id: "anx-13",
      text: "Who would you be without the worry? Not who would you be if it stopped — who are you underneath it?",
      pattern: "anxiety",
      timeOfDay: "any",
      type: "reflection",
    },
  ],
  depression: [
    {
      id: "dep-1",
      text: "Was there any moment today where you felt even slightly more like yourself?",
      followUp: "Don't judge it. A good sandwich, a song, a random thought — all count.",
      pattern: "depression",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "dep-2",
      text: "What would make today 5% less heavy? Not fixed. Just slightly lighter.",
      pattern: "depression",
      timeOfDay: "morning",
      type: "action",
    },
    {
      id: "dep-3",
      text: "When was your best hour today? What were you doing?",
      followUp: "Can we try to protect that time tomorrow?",
      pattern: "depression",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "dep-4",
      text: "What took more effort than it should have today? Name it so it counts.",
      pattern: "depression",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "dep-5",
      text: "What's something that's not broken right now? Even if it feels small.",
      pattern: "depression",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "dep-6",
      text: "Did you get outside today at all? What did the air feel like?",
      followUp: "You don't need to go far. The mailbox counts. The porch counts.",
      pattern: "depression",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "dep-7",
      text: "What's one thing you don't have to do today? Not something you're avoiding. Something you can genuinely let go of.",
      followUp: "Say it out loud: 'I don't have to do that today.'",
      pattern: "depression",
      timeOfDay: "morning",
      type: "action",
    },
    {
      id: "dep-8",
      text: "When did you go quiet today? Not peaceful quiet. The kind where you disappear a little.",
      followUp: "What was happening right before that? Can you spot the trigger?",
      pattern: "depression",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "dep-9",
      text: "Name three things you did today that took effort. Brushing your teeth counts. Eating counts. Getting up counts.",
      followUp: "Those aren't nothing. That's your brain carrying weights and still moving.",
      pattern: "depression",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "dep-10",
      text: "What would you tell someone you love who felt the way you feel right now?",
      followUp: "Now read it back to yourself.",
      pattern: "depression",
      timeOfDay: "any",
      type: "action",
    },
    {
      id: "dep-11",
      text: "Is the heaviness today a specific thing or just... there? Like weather, not an event.",
      followUp: "Weather passes. You don't have to fix it. You just have to get through it.",
      pattern: "depression",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "dep-12",
      text: "What's one tiny kindness you can do for yourself in the next hour?",
      followUp: "Not earn. Not deserve. Just do.",
      pattern: "depression",
      timeOfDay: "any",
      type: "action",
    },
    {
      id: "dep-13",
      text: "What did your body need today that you couldn't give it? What about tomorrow?",
      pattern: "depression",
      timeOfDay: "evening",
      type: "tracking",
    },
  ],
  autism: [
    {
      id: "aut-1",
      text: "How much social energy did you spend today? 0 (didn't talk to anyone) to 100 (fully depleted).",
      followUp: "Did you mask? What did that cost you today?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "aut-2",
      text: "What sensory stuff was hard today? Lights, sounds, textures, smells — any of it.",
      followUp: "What would have made that easier?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "aut-3",
      text: "What do you want to infodump about right now? Just go. No structure needed.",
      pattern: "autism",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "aut-4",
      text: "Did anything break your routine today? How did that feel in your body?",
      followUp: "What helped you recover from it, if anything?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "aut-5",
      text: "Where were you today where you felt most like yourself?",
      pattern: "autism",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "aut-6",
      text: "Was there a moment today where someone said something ambiguous and you weren't sure what they meant? What did you do?",
      followUp: "Did you ask for clarification or did you just guess? How'd that go?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "aut-7",
      text: "What's your current special interest hyperfixation? What's the latest thing you've learned about it?",
      followUp: "Don't summarize. Give me the details. The good ones.",
      pattern: "autism",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "aut-8",
      text: "Did you stim today? What kind? Was it conscious or did you catch yourself doing it?",
      followUp: "Stimming isn't a symptom. It's regulation. What were you regulating?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "aut-9",
      text: "When did you feel overwhelmed today? What was piling up right before it hit?",
      followUp: "Can you identify the last straw, or was it everything at once?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "aut-10",
      text: "What environment felt good today? Not just tolerable — actually good. What made it work?",
      followUp: "Can you engineer more of that into tomorrow?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "aut-11",
      text: "Did you have any moments of quiet joy today? Something only you would notice or appreciate?",
      followUp: "Those moments are real. They count even if nobody else saw them.",
      pattern: "autism",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "aut-12",
      text: "How much did you mask today? 0 (fully myself) to 100 (complete performance).",
      followUp: "What would it look like to drop that number by 10 tomorrow? Where's the safest place to do it?",
      pattern: "autism",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "aut-13",
      text: "What's something you know an unreasonable amount of detail about that came up today?",
      followUp: "That's not a flaw. That's your brain at its best. Write it down.",
      pattern: "autism",
      timeOfDay: "any",
      type: "reflection",
    },
  ],
  ptsd: [
    {
      id: "ptsd-1",
      text: "Right now: 5 things you can see, 4 you can hear, 3 you can touch, 2 you can smell.",
      followUp: "You're here. In this moment, you're safe.",
      pattern: "ptsd",
      timeOfDay: "any",
      type: "grounding",
    },
    {
      id: "ptsd-2",
      text: "What did your body do today that caught you off guard? Jumped, tensed, shut down?",
      followUp: "Your nervous system was trying to protect you. What was it reacting to?",
      pattern: "ptsd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "ptsd-3",
      text: "Where in your body do you feel safe right now? Even one spot.",
      pattern: "ptsd",
      timeOfDay: "any",
      type: "grounding",
    },
    {
      id: "ptsd-4",
      text: "What did you avoid today? No judgment. Just name it.",
      followUp: "What would feel safe about approaching that thing?",
      pattern: "ptsd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "ptsd-5",
      text: "Did you sleep okay last night? Nightmares, waking up, or just couldn't turn off?",
      followUp: "What was the last thing you were thinking about before sleep?",
      pattern: "ptsd",
      timeOfDay: "morning",
      type: "tracking",
    },
    {
      id: "ptsd-6",
      text: "Was there a trigger today? Something that pulled you out of the present and somewhere else?",
      followUp: "You don't have to name the memory. Just name the trigger.",
      pattern: "ptsd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "ptsd-7",
      text: "Right now: press your feet into the floor. Feel it. Now look around the room. You are not there. You are here.",
      followUp: "Say it: 'I am here. This is now. That was then.'",
      pattern: "ptsd",
      timeOfDay: "any",
      type: "grounding",
    },
    {
      id: "ptsd-8",
      text: "Who or what made you feel safe today? Not comfortable. Safe.",
      followUp: "What was it about them or it that let your guard down?",
      pattern: "ptsd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "ptsd-9",
      text: "What did your inner protector do today? Did it push people away, keep you hyper-aware, shut you down?",
      followUp: "It's trying to keep you safe. Is it using strategies that made sense then but not now?",
      pattern: "ptsd",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "ptsd-10",
      text: "What's one thing in your current environment that would not have been safe in the past?",
      followUp: "Let yourself notice that difference. You built this. You're allowed to be in it.",
      pattern: "ptsd",
      timeOfDay: "any",
      type: "grounding",
    },
    {
      id: "ptsd-11",
      text: "How much of today did you spend scanning for threats? 0 (none) to 10 (constant vigilance).",
      followUp: "What would it feel like to let that drop by one point tomorrow? Just one.",
      pattern: "ptsd",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "ptsd-12",
      text: "What emotion came up today that you tried to push down? Where did you feel it in your body?",
      followUp: "You don't have to explain it. Just let it be there for a minute.",
      pattern: "ptsd",
      timeOfDay: "any",
      type: "reflection",
    },
  ],
  bipolar: [
    {
      id: "bip-1",
      text: "Sleep last night: how much and how good? Energy today: low, steady, or running hot?",
      pattern: "bipolar",
      timeOfDay: "morning",
      type: "tracking",
    },
    {
      id: "bip-2",
      text: "How fast are your thoughts moving right now? Slow, normal, or like a browser with 50 tabs?",
      followUp: "If racing: when did this start? What shifted?",
      pattern: "bipolar",
      timeOfDay: "any",
      type: "tracking",
    },
    {
      id: "bip-3",
      text: "Are you in an up or down right now? What are you doing with that energy (or lack of it)?",
      pattern: "bipolar",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "bip-4",
      text: "Did you start anything new today? A project, a plan, a purchase, a commitment? How'd that feel?",
      followUp: "Is this a real interest or is this the energy talking? Give it 48 hours.",
      pattern: "bipolar",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "bip-5",
      text: "Rate today: mood (1-10), energy (1-10), sleep quality last night (1-10). Quick numbers, no essay.",
      followUp: "Over time, these numbers tell a story. You're building your own data set.",
      pattern: "bipolar",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "bip-6",
      text: "Are you spending differently than usual lately? Bigger purchases, more impulsive, or the opposite?",
      followUp: "Not a judgment. Just a pattern to notice.",
      pattern: "bipolar",
      timeOfDay: "any",
      type: "tracking",
    },
    {
      id: "bip-7",
      text: "When did you last feel stable? Not up, not down. Just... level. What was that like?",
      followUp: "What was different about that period? What was the same?",
      pattern: "bipolar",
      timeOfDay: "any",
      type: "reflection",
    },
    {
      id: "bip-8",
      text: "What's the gap between how much you want to do right now and how much you actually should do?",
      followUp: "If the gap is huge, that's worth noting. If it's tiny, that's worth celebrating.",
      pattern: "bipolar",
      timeOfDay: "morning",
      type: "action",
    },
    {
      id: "bip-9",
      text: "Have you been more talkative than usual? Faster? Louder? Or quieter than your baseline?",
      followUp: "Who noticed? Did they say anything?",
      pattern: "bipolar",
      timeOfDay: "evening",
      type: "tracking",
    },
    {
      id: "bip-10",
      text: "What's your irritability like today? 0 (zen) to 10 (everything is too much)?",
      followUp: "What's the gap between your irritability and what's actually happening around you?",
      pattern: "bipolar",
      timeOfDay: "any",
      type: "tracking",
    },
    {
      id: "bip-11",
      text: "If you charted your last two weeks as a line graph, what would it look like? Describe the shape.",
      followUp: "Is it steady, spiky, climbing, dropping? No wrong answers.",
      pattern: "bipolar",
      timeOfDay: "evening",
      type: "reflection",
    },
    {
      id: "bip-12",
      text: "What did you commit to today that you might not want to do when your energy shifts?",
      followUp: "You're allowed to change your mind when the landscape changes. That's not flaky. That's honest.",
      pattern: "bipolar",
      timeOfDay: "any",
      type: "action",
    },
  ],
};

// Build a plan from whatever patterns have been identified so far
export function generatePlan(topPatterns: string[]): { patterns: string[]; prompts: JournalPrompt[] } {
  const prompts: JournalPrompt[] = [];
  for (const pattern of topPatterns) {
    const patternPrompts = promptLibrary[pattern] ?? [];
    prompts.push(...patternPrompts);
  }
  return { patterns: topPatterns, prompts };
}

// Get two prompt choices for the user
export function getDailyPromptChoices(
  plan: { prompts: JournalPrompt[] },
  dayOffset: number = 0
): [JournalPrompt, JournalPrompt] {
  const pool = plan.prompts;
  if (pool.length < 2) {
    return [pool[0], pool[0]];
  }
  const baseIdx = (new Date().getDate() + dayOffset) % pool.length;
  const secondIdx = (baseIdx + Math.max(1, Math.floor(pool.length / 2))) % pool.length;
  return [pool[baseIdx], pool[secondIdx]];
}
